### ISSUE TITLE
kf_sine_demo missing

### ISSUE THREAD

**Issue by sursu** [EEA-sensors/ekfukf#4]
I think the `demo` folder is missing the `kf_sine_demo`.

**Comment by RoyiAvital** [comment]
Where is the documentation PDF?

**Comment by zgbkdlm** [comment]
The missing demo `kf_sine_demo` was added. The corresponding material can be found in Simo's book or the course notes.

**Comment by RoyiAvital** [comment]
The documentation of the toolbox should be part of it (It is available here: https://www.researchgate.net/publication/228683456).
I think for completeness it is better have it in the repository (You may use GIT LFS).
